# .github/dependabot.yml
version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "github-actions"

  # Keep root Node.js/PNPM deps fresh
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "npm"

  # Keep each package/* deps fresh (monorepo aware)
  - package-ecosystem: "npm"
    directory: "/packages/*"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "npm"

  # Optionally keep docs deps up to date
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "docs"
