name: CI
on:
  push:
    paths:
      - 'templates/**'
      - '.github/workflows/ci.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm -C templates/widget-starter lint
      - run: pnpm -C templates/widget-starter build
