name: Release (tagged)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile || pnpm install

      - name: Build project(s)
        run: pnpm -r run build || pnpm run build || true

      - name: Prepare release zips
        run: |
          mkdir -p release-zips
          # Collect built package zips if any
          find packages -type f -name "*.zip" -exec cp {} release-zips/ \; || true
          # Otherwise zip repo contents as fallback
          if [ "$(ls -A release-zips)" = "" ]; then
            zip -r release-zips/repository.zip . -x ".git/*" "node_modules/*" "packages/*/node_modules/*"
          fi
          ls -la release-zips

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-zips/*.zip
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
